version: '3.8'

services:
  test_db:
    image: docker.io/library/postgres:17
    volumes:
      - postgres_test_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=neurons_testing
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  test_backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - TEST_DATABASE_URL=postgresql://postgres:postgres@test_db:5432/neurons_testing
    depends_on:
      test_db:
        condition: service_healthy
    command: pytest


volumes:
  postgres_test_data:
